final List<String> allCategories = [
'Agricultura / ganadería',
'Artista',
'Belleza / cosmética',
'Cine / tv',
'Compras y ventas',
'Consultorio odontológico',
'Creador digital',
'Editor',
'Educación',
'Electrónica e informática',
'Emprendedor(a)',
'Espectáculos / eventos',
'Farmacia y Droguería',
'Ferretería y Construcción',
'Fotógrafo(a)',
'Hoteles y turismo',
'Industria o manufactura',
'Licorería',
'Músico / Banda',
'Papelería / Miscelánea',
'Regalos sorpresa',
'Ropa (marca)',
'Zapatos y accesorios',
'Salud / belleza',
'Servicio a vehículos',
'Transporte y logística',
'Servicios profesionales',
'Servicios financieros',
'Supermercado',
'Taller automotriz',
'Teatro',
'Tienda comestibles',
'Tienda de mascotas',
'Tienda naturista',
'Venta Juguetes / libros',
'Venta de textiles',
'Venta por catálogo'
'Otro',
  ];